print ('================= Desafio 9 =================')
numero = int(input('Digite um Numero para ver sua Tabuada: '))
print('-' * 20)
print(f'{numero :2} *  1 = {numero * 1 :2}')
print(f'{numero :2} *  2 = {numero * 2}')
print(f'{numero :2} *  3 = {numero * 3}')
print(f'{numero :2} *  4 = {numero * 4}')
print(f'{numero :2} *  5 = {numero * 5}')
print(f'{numero :2} *  6 = {numero * 6}')
print(f'{numero :2} *  7 = {numero * 7}')
print(f'{numero :2} *  8 = {numero * 8}')
print(f'{numero :2} *  9 = {numero * 9}')
print(f'{numero :2} * 10 = {numero * 10}')
print('-' * 20)
